on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  nix:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Flake Tests
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Build all test projects
        run: |
          for project in ./testProjects/*/; do
            pushd $project
            nix build -L
            popd
          done

      - name: Ensure binary can be ran
        run: result/bin/testProject
        working-directory: testProjects/testProject/
