on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  nix:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Flake Tests
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3.22.2
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Build all test projects
        run: |
          for project in ./testProjects/*/; do
            echo "::group::Testing $project"
            pushd $project
            nix build -L
            popd
            echo "::endgroup::"
          done

      - name: Ensure binary can be ran
        run: result/bin/testProject
        working-directory: testProjects/testProject/

      - name: Test a dev environment can be used
        working-directory: testProjects/testProject
        run: |
          nix develop -c nim r src/testProject.nim
          # I don't recommend using nimble...
          # nix develop -c nimble test

      - name: Test actual app
        run: |
          git clone https://github.com/ire4ever1190/nimsight
          cd nimsight
          # Make it be part of current repo so it can access the flake
          rm -rf .git
          git add .

          # Make it point to the current version of the flake
          sed -i 's@github:ire4ever1190/mkNimbleApp@path:../@' flake.nix

          nix build -L
